name: Upload build package into Artifact

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
      - name: Archive
        run: tar czf neo-pkg-web-example.tar.gz ./build/
      - name: Release files
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./neo-pkg-web-example.tar.gz
          repo_name: machbase/neo-pkg-web-example
          prerelease: true
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: false
