name: Upload build package into Artifact

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - run: npm install
      - run: npm run build

      - name: Archive
        run: cd ./build && zip -r neo-pkg-web-example.zip ./*
      - name: Release files
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          repo_token: ${{ secrets.GIT_PASS }}
          file: ./build/neo-pkg-web-example.zip
          repo_name: machbase/neo-pkg-web-example
          prerelease: true
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: false
